const devicesTypes = {
  FETCH_DEVICES_REQUEST: "FETCH_DEVICES_REQUEST",
  FETCH_DEVICES_SUCCESS: "FETCH_DEVICES_SUCCESS",
  FETCH_DEVICES_FAILURE: "FETCH_DEVICES_FAILURE",
};

export default devicesTypes;
